# Generated by Django 5.2.5 on 2025-08-10 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='visibility',
            field=models.CharField(blank=True, choices=[('PUBLIC', 'public'), ('PRIVATE', 'private')], null=True),
        ),
    ]
