# Generated by Django 5.2.5 on 2025-08-10 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_visibility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='visibility',
        ),
    ]
