# Generated by Django 5.2.5 on 2025-08-10 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_post_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='article_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='article_title',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='article_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
