# Generated by Django 5.2.5 on 2025-08-10 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_media_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='media_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='media_title',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
