# Generated by Django 5.2.5 on 2025-08-11 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_media_description_post_media_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='article_description',
        ),
        migrations.RemoveField(
            model_name='post',
            name='media_description',
        ),
        migrations.RemoveField(
            model_name='post',
            name='media_title',
        ),
        migrations.AlterField(
            model_name='post',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('failed', 'Failed'), ('scheduled', 'Scheduled')], default='draft', max_length=64),
        ),
    ]
